version: "3"

networks:
  sspanel:

volumes:
  redis_aof:

services:
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/vpc123/nginx:1.7.9
    environment:
      TZ: Asia/Shanghai
    restart: always
    container_name: nginx
    volumes:
      - ./configs/nginx/:/etc/nginx/conf.d
      - .:/usr/src/app
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - sspanel
  redis:
    image: registry.cn-hangzhou.aliyuncs.com/vpc123/redis:6.0
    container_name: redis
    restart: always
    volumes:
      - redis_aof:/var/data/redis
    networks:
      - sspanel
  web:
    container_name: web
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/vpc123/django-sspanel:runtime
    environment:
      DJANGO_ENV: production
      TZ: Asia/Shanghai
      REDIS_HOST: redis
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    networks:
      - sspanel
    ports:
      - 8080:8080
    working_dir: /usr/src/app
    command: uwsgi uwsgi.ini
  celery-worker:
    container_name: celery-worker
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/vpc123/django-sspanel:runtime
    environment:
      DJANGO_ENV: production
      REDIS_HOST: redis
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    networks:
      - sspanel
    working_dir: /usr/src/app
    command:
      - celery
      - -A
      - apps
      - worker
      - -l
      - info
  # 定时任务
  celery-beat:
    container_name: celery-beat
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/vpc123/django-sspanel:runtime
    environment:
      DJANGO_ENV: production
      REDIS_HOST: redis
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    networks:
      - sspanel
    working_dir: /usr/src/app
    command:
      - celery
      - -A
      - apps
      - beat
      - -l
      - info
